[package]
name = "chat-req-res"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
libp2p = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
